# Generated by Django 5.1.3 on 2025-01-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('detail', models.TextField(verbose_name='detail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('affiliate_url', models.URLField(verbose_name='affiliate url')),
                ('image_url', models.URLField(verbose_name='image url')),
                ('tags', models.ManyToManyField(to='product.tag', verbose_name='tags')),
            ],
        ),
    ]
